import { spawn } from 'node:child_process'
import { existsSync } from 'node:fs'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'

const port=3399
const base=`http://127.0.0.1:${port}/api`
const dataDir=await mkdtemp(join(tmpdir(),'autoflow-queue-test-'))
const extensionOne='test_extension_instance_alpha'
const extensionTwo='test_extension_instance_beta'
const server=spawn(process.execPath,['server/server.ts'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),DATA_DIR:dataDir,AUTH_SECRET:'queue-test-secret'},stdio:['ignore','pipe','pipe']})
let serverOutput=''
server.stdout.on('data',chunk=>serverOutput+=chunk)
server.stderr.on('data',chunk=>serverOutput+=chunk)

async function waitForServer(){for(let attempt=0;attempt<40;attempt++){try{const response=await fetch(base+'/health');if(response.ok)return}catch{/* API ainda inicializando */}await new Promise(resolve=>setTimeout(resolve,100))}throw new Error(`A API de teste não iniciou. ${serverOutput}`)}
async function login(email){const response=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password:'demo1234'})});const data=await response.json();if(!response.ok)throw new Error(data.error);return data.token}
async function call(path,token,options={}){const response=await fetch(base+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`}});const data=await response.json();if(!response.ok)throw Object.assign(new Error(`${response.status} ${path}: ${data.error}`),{status:response.status,body:data});return data}
async function expectStatus(status,operation){try{await operation();throw new Error(`A operação deveria responder ${status}.`)}catch(error){if(error.status!==status)throw error}}

try{
  await waitForServer()
  const adminToken=await login('admin@autoflow.local')
  const sellerToken=await login('marina@autoflow.local')
  const team=await call('/team',adminToken)
  const admin=team.users.find(user=>user.email==='admin@autoflow.local')
  const marina=team.users.find(user=>user.email==='marina@autoflow.local')
  const first=await call('/social-accounts',adminToken,{method:'POST',body:JSON.stringify({userId:admin.id,label:'Facebook Daniel',browserProfile:'Brave Perfil 1'})})
  const second=await call('/social-accounts',adminToken,{method:'POST',body:JSON.stringify({userId:marina.id,label:'Facebook Marina',browserProfile:'Brave Perfil 2'})})
  await call('/settings',adminToken,{method:'PATCH',body:JSON.stringify({organizationName:'AutoPrime Veículos',defaultLocation:'São Paulo, SP',dailyLimit:10,descriptionTemplate:'',autoAdvance:true,fillGroups:true,targetGroups:['Compra-se e Vende-se | https://www.facebook.com/groups/123456','Carros e Motos Criciúma e Região'],autoPublish:false})})
  await call('/settings',adminToken,{method:'PATCH',body:JSON.stringify({organizationName:'AutoPrime Veículos',defaultLocation:'São Paulo, SP',dailyLimit:10,stuckTimeoutMinutes:1,descriptionTemplate:'',autoAdvance:true,fillGroups:true,groups:[{name:'Compra-se e Vende-se',url:'https://www.facebook.com/groups/123456',active:true,priority:1},{name:'Carros e Motos Criciúma e Região',url:'',active:true,priority:2}],autoPublish:false})})
  const structuredSettings=await call('/settings',adminToken)
  if(structuredSettings.settings.groups.length!==2||structuredSettings.settings.groups[0].groupKey!=='123456'||structuredSettings.settings.groups[0].priority!==1)throw new Error('O gerenciador estruturado de grupos nao preservou ID e prioridade.')
  await expectStatus(400,()=>call('/settings',adminToken,{method:'PATCH',body:JSON.stringify({organizationName:'AutoPrime Veículos',defaultLocation:'São Paulo, SP',dailyLimit:10,descriptionTemplate:'',autoAdvance:true,fillGroups:true,groups:[{name:'Grupo invalido',url:'https://example.com/groups/1',active:true}],autoPublish:false})}))
  await expectStatus(403,()=>call('/social-accounts',sellerToken,{method:'POST',body:JSON.stringify({userId:marina.id,label:'Não permitido',browserProfile:'Brave Perfil 3'})}))
  const sellerAccounts=await call('/extension/accounts',sellerToken)
  if(sellerAccounts.accounts.length!==1||sellerAccounts.accounts[0].id!==second.id)throw new Error('O vendedor recebeu perfis de outro usuário.')
  await expectStatus(403,()=>call(`/extension/queue?accountId=${first.id}`,sellerToken))
  await expectStatus(400,()=>call('/vehicles',adminToken,{method:'POST',body:JSON.stringify({year:2024,make:'Marca inventada',model:'Teste',price:50000,km:100,vehicleType:'Carro/picape',location:'São Paulo, SP',transmission:'Automático',fuelType:'Flex',bodyType:'Sedã',condition:'Excelente',exteriorColor:'Prateado',interiorColor:'Preto',description:'Teste de validação',status:'Rascunho'})}))

  try{
    await call('/publications',adminToken,{method:'POST',body:JSON.stringify({vehicleId:4,accountId:first.id})})
    throw new Error('A publicação deveria ter sido bloqueada por falta de fotos.')
  }catch(error){
    if(error.status!==422||!error.body?.missing?.includes('Fotos'))throw error
  }
  const blockedVehicle=(await call('/vehicles',adminToken)).vehicles.find(item=>item.id===4)
  if(blockedVehicle.status!=='Atenção')throw new Error('O veículo incompleto não foi marcado como Atenção.')

  const imageOne=await call('/vehicles/1/images',adminToken,{method:'POST',body:JSON.stringify({name:'foto-1.jpg',mimeType:'image/jpeg',dataBase64:Buffer.from('foto-um').toString('base64')})})
  const imageTwo=await call('/vehicles/1/images',adminToken,{method:'POST',body:JSON.stringify({name:'foto-2.jpg',mimeType:'image/jpeg',dataBase64:Buffer.from('foto-dois').toString('base64')})})
  const orderedBefore=(await call('/vehicles/1/images',adminToken)).images.map(item=>item.id)
  if(orderedBefore[0]!==imageOne.id||orderedBefore[1]!==imageTwo.id)throw new Error('A ordem inicial das fotos não respeitou o upload.')
  await call('/vehicles/1/images/reorder',adminToken,{method:'PATCH',body:JSON.stringify({order:[imageTwo.id,imageOne.id]})})
  const orderedAfter=(await call('/vehicles/1/images',adminToken)).images.map(item=>item.id)
  if(orderedAfter[0]!==imageTwo.id||orderedAfter[1]!==imageOne.id)throw new Error('A reordenação de fotos não foi aplicada.')
  await expectStatus(400,()=>call('/vehicles/1/images/reorder',adminToken,{method:'PATCH',body:JSON.stringify({order:[imageOne.id]})}))

  const vehicleOne=(await call('/vehicles',adminToken)).vehicles.find(item=>item.id===1)
  await call('/vehicles/1',adminToken,{method:'PATCH',body:JSON.stringify({...vehicleOne,condition:'Excelente',exteriorColor:'Prateado',interiorColor:'Preto',status:'Pronto'})})

  const publication=await call('/publications',adminToken,{method:'POST',body:JSON.stringify({vehicleId:1,accountId:first.id})})
  await expectStatus(409,()=>call('/publications',adminToken,{method:'POST',body:JSON.stringify({vehicleId:1,accountId:second.id})}))
  const priorityVehicle=await call('/vehicles',adminToken,{method:'POST',body:JSON.stringify({year:2024,make:'Chevrolet',model:'Tracker',trim:'Premier',price:154900,km:8900,vehicleType:'Carro/picape',location:'São Paulo, SP',transmission:'Automático',fuelType:'Flex',bodyType:'SUV',condition:'Excelente',exteriorColor:'Prateado',interiorColor:'Preto',description:'Veículo para testar prioridade da fila.',status:'Pronto'})})
  await call(`/vehicles/${priorityVehicle.id}/images`,adminToken,{method:'POST',body:JSON.stringify({name:'prioridade.jpg',mimeType:'image/jpeg',dataBase64:Buffer.from('foto-prioridade').toString('base64')})})
  const priorityPublication=await call('/publications',adminToken,{method:'POST',body:JSON.stringify({vehicleId:priorityVehicle.id,accountId:first.id})})
  const batchStart=new Date(Date.now()+2*3600000).toISOString()
  const batchSchedule=await call('/publications/schedule-batch',adminToken,{method:'PATCH',body:JSON.stringify({ids:[publication.id,priorityPublication.id],startAt:batchStart,intervalMinutes:20})})
  if(batchSchedule.assignments.length!==2||Date.parse(batchSchedule.assignments[1].scheduledAt)-Date.parse(batchSchedule.assignments[0].scheduledAt)<20*60000)throw new Error('O agendamento em sequência não respeitou o intervalo mínimo.')
  let batchQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(batchQueue.jobs.some(item=>[publication.id,priorityPublication.id].includes(item.jobId)))throw new Error('Trabalhos agendados em sequência apareceram antes do horário.')
  for(const id of [publication.id,priorityPublication.id])await call(`/publications/${id}/schedule`,adminToken,{method:'PATCH',body:JSON.stringify({scheduledAt:null})})
  await expectStatus(400,()=>call('/publications/schedule-batch',adminToken,{method:'PATCH',body:JSON.stringify({ids:[publication.id],startAt:batchStart,intervalMinutes:20})}))
  let firstQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  const secondQueue=await call(`/extension/queue?accountId=${second.id}`,adminToken)
  if(firstQueue.jobs.length!==2||firstQueue.jobs[0].jobId!==publication.id)throw new Error('A fila inicial não respeitou a ordem de inclusão.')
  if(secondQueue.jobs.length!==0)throw new Error('O trabalho vazou para outro perfil.')
  await call(`/publications/${priorityPublication.id}/priority`,adminToken,{method:'PATCH',body:JSON.stringify({direction:'up'})})
  firstQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(firstQueue.jobs[0].jobId!==priorityPublication.id)throw new Error('A prioridade não alterou a ordem recebida pela extensão.')
  await call('/publications/queue-state',adminToken,{method:'PATCH',body:JSON.stringify({ids:[priorityPublication.id],action:'pause'})})
  firstQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(firstQueue.jobs.length!==1||firstQueue.jobs[0].jobId!==publication.id)throw new Error('O trabalho pausado continuou disponível na extensão.')
  await expectStatus(409,()=>call(`/extension/jobs/${priorityPublication.id}/prepare`,adminToken,{method:'POST',body:JSON.stringify({accountId:first.id,instanceId:extensionOne})}))
  await call('/publications/queue-state',adminToken,{method:'PATCH',body:JSON.stringify({ids:[priorityPublication.id],action:'resume'})})
  firstQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(firstQueue.jobs[0].jobId!==priorityPublication.id)throw new Error('Retomar não devolveu o trabalho à posição preservada da fila.')
  const scheduledFor=new Date(Date.now()+3600000).toISOString()
  await call(`/publications/${priorityPublication.id}/schedule`,adminToken,{method:'PATCH',body:JSON.stringify({scheduledAt:scheduledFor})})
  firstQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(firstQueue.jobs.length!==1||firstQueue.jobs[0].jobId!==publication.id)throw new Error('O trabalho agendado apareceu na extensão antes do horário.')
  const scheduledJob=(await call('/publications',adminToken)).jobs.find(item=>item.id===priorityPublication.id)
  if(!scheduledJob.scheduledAt||Date.parse(scheduledJob.scheduledAt)!==Date.parse(scheduledFor))throw new Error('O horário agendado não foi persistido.')
  await expectStatus(409,()=>call(`/extension/jobs/${priorityPublication.id}/prepare`,adminToken,{method:'POST',body:JSON.stringify({accountId:first.id,instanceId:extensionOne})}))
  await call(`/publications/${priorityPublication.id}/schedule`,adminToken,{method:'PATCH',body:JSON.stringify({scheduledAt:null})})
  firstQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(firstQueue.jobs[0].jobId!==priorityPublication.id)throw new Error('Remover o agendamento não liberou o trabalho imediatamente.')
  await expectStatus(400,()=>call(`/publications/${priorityPublication.id}/schedule`,adminToken,{method:'PATCH',body:JSON.stringify({scheduledAt:new Date(Date.now()-3600000).toISOString()})}))
  await expectStatus(403,()=>call('/publications/reassign',sellerToken,{method:'PATCH',body:JSON.stringify({ids:[priorityPublication.id],accountId:second.id})}))
  await call('/publications/reassign',adminToken,{method:'PATCH',body:JSON.stringify({ids:[priorityPublication.id],accountId:second.id})})
  firstQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  let reassignedQueue=await call(`/extension/queue?accountId=${second.id}`,adminToken)
  if(firstQueue.jobs.some(item=>item.jobId===priorityPublication.id)||reassignedQueue.jobs[0]?.jobId!==priorityPublication.id)throw new Error('A redistribuiÃ§Ã£o nÃ£o moveu o trabalho entre os perfis.')
  let reassignedJob=(await call('/publications',adminToken)).jobs.find(item=>item.id===priorityPublication.id)
  if(reassignedJob.accountId!==second.id||reassignedJob.previousAccountLabel!=='Facebook Daniel')throw new Error('A fila nÃ£o preservou a origem da redistribuiÃ§Ã£o.')
  await call('/publications/reassign',adminToken,{method:'PATCH',body:JSON.stringify({ids:[priorityPublication.id],accountId:first.id})})
  reassignedQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(!reassignedQueue.jobs.some(item=>item.jobId===priorityPublication.id))throw new Error('O trabalho nÃ£o voltou ao perfil original apÃ³s nova redistribuiÃ§Ã£o.')
  await expectStatus(400,()=>call('/publications/reassign',adminToken,{method:'PATCH',body:JSON.stringify({ids:[priorityPublication.id],accountId:first.id})}))
  await call(`/publications/${priorityPublication.id}`,adminToken,{method:'PATCH',body:JSON.stringify({status:'canceled'})})
  const priorityTimeline=await call(`/publications/${priorityPublication.id}/timeline`,adminToken)
  const priorityEvents=new Set(priorityTimeline.events.map(event=>event.eventType))
  for(const type of ['created','batch_scheduled','priority_changed','paused','resumed','scheduled','schedule_removed','reassigned','canceled'])if(!priorityEvents.has(type))throw new Error(`O histórico da fila não registrou o evento ${type}.`)
  if(!priorityTimeline.events.some(event=>event.eventType==='reassigned'&&event.fromAccount&&event.toAccount))throw new Error('O histórico não identificou os perfis da redistribuição.')
  const prepared=await call(`/extension/jobs/${publication.id}/prepare`,adminToken,{method:'POST',body:JSON.stringify({accountId:first.id,instanceId:extensionOne})})
  if(!prepared.leaseToken||prepared.leaseSeconds!==120)throw new Error('A reserva exclusiva não foi entregue à extensão.')
  await expectStatus(409,()=>call(`/extension/jobs/${publication.id}/prepare`,adminToken,{method:'POST',body:JSON.stringify({accountId:first.id,instanceId:extensionTwo})}))
  const lockedQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(!lockedQueue.jobs.find(item=>item.jobId===publication.id)?.locked)throw new Error('A fila não sinalizou que o trabalho está em uso por outra aba.')
  await expectStatus(409,()=>call(`/extension/jobs/${publication.id}/heartbeat`,adminToken,{method:'POST',body:JSON.stringify({leaseToken:'token-incorreto'})}))
  await call(`/extension/jobs/${publication.id}/heartbeat`,adminToken,{method:'POST',body:JSON.stringify({leaseToken:prepared.leaseToken})})
  await expectStatus(409,()=>call(`/extension/jobs/${publication.id}/fill-result`,adminToken,{method:'PATCH',body:JSON.stringify({leaseToken:'token-incorreto',error:'Resultado de outra aba'})}))
  await expectStatus(409,()=>call('/publications/reassign',adminToken,{method:'PATCH',body:JSON.stringify({ids:[publication.id],accountId:second.id})}))
  const automationOverview=await call('/automation/overview',adminToken)
  const automationProfile=automationOverview.profiles.find(profile=>profile.id===first.id)
  if(!automationProfile||automationProfile.stage!=='Preenchendo dados'||automationProfile.currentJob?.id!==publication.id||automationProfile.currentJob?.attemptCount!==1)throw new Error('A Central de automacao nao refletiu o trabalho em andamento.')
  if(prepared.vehicle.interiorColor!=='Preto')throw new Error('A cor interna não chegou à extensão.')
  if(prepared.vehicle.condition!=='Excelente')throw new Error('A condição do veículo não chegou à extensão.')
  if(!prepared.automation.autoAdvance||!prepared.automation.fillGroups||prepared.automation.autoPublish||prepared.automation.targetGroups.length!==2)throw new Error('As regras de automação não chegaram à extensão.')
  await call(`/extension/jobs/${publication.id}/fill-result`,adminToken,{method:'PATCH',body:JSON.stringify({leaseToken:prepared.leaseToken,error:'Falha temporária antes do teste de recuperação',extensionVersion:'0.11.0'})})
  let issueReport=await call('/reports/issues',adminToken)
  const activeExecutionError=issueReport.issues.find(item=>item.jobId===publication.id&&item.category==='execution')
  if(!activeExecutionError?.active||activeExecutionError.severity!=='error'||activeExecutionError.extensionVersion!=='0.11.0')throw new Error('O relatório não registrou o erro ativo da extensão.')
  await call(`/publications/${publication.id}`,adminToken,{method:'PATCH',body:JSON.stringify({status:'pending'})})
  const recoveryPrepared=await call(`/extension/jobs/${publication.id}/prepare`,adminToken,{method:'POST',body:JSON.stringify({accountId:first.id,instanceId:extensionOne})})
  await expectStatus(403,()=>call(`/publications/${publication.id}/recover`,sellerToken,{method:'POST'}))
  await expectStatus(409,()=>call(`/publications/${publication.id}/recover`,adminToken,{method:'POST'}))
  const testDb=new DatabaseSync(join(dataDir,'autoflow.db'))
  testDb.prepare("UPDATE publication_jobs SET started_at=datetime('now','-2 minutes') WHERE id=?").run(publication.id)
  await expectStatus(409,()=>call(`/publications/${publication.id}/recover`,adminToken,{method:'POST'}))
  testDb.prepare("UPDATE publication_jobs SET lease_expires_at=datetime('now','-1 second') WHERE id=?").run(publication.id)
  testDb.close()
  await call(`/publications/${publication.id}/recover`,adminToken,{method:'POST'})
  let recovered=(await call('/publications',adminToken)).jobs.find(item=>item.id===publication.id)
  if(recovered.status!=='pending')throw new Error('A recuperação não devolveu o trabalho travado para a fila.')
  if(!recoveryPrepared.leaseToken)throw new Error('A segunda execução não recebeu uma nova reserva.')
  const reviewPrepared=await call(`/extension/jobs/${publication.id}/prepare`,adminToken,{method:'POST',body:JSON.stringify({accountId:first.id,instanceId:extensionOne})})
  await call(`/extension/jobs/${publication.id}/fill-result`,adminToken,{method:'PATCH',body:JSON.stringify({leaseToken:reviewPrepared.leaseToken,filledCount:14,totalCount:15,imageCount:7,missing:['Cor interna'],fields:[{name:'Cor interna',ok:false}],advanced:true,selectedGroups:[],missingGroups:[],flowIssues:['O Facebook recebeu o clique em Publicar, mas não confirmou o resultado.'],published:false,publishAttempted:true,extensionVersion:'0.12.0'})})
  let job=(await call('/publications',adminToken)).jobs.find(item=>item.id===publication.id)
  if(job.status!=='awaiting_confirmation'||job.fillReport?.missing?.[0]!=='Cor interna'||job.fillReport?.flowIssues?.length!==1)throw new Error('O relatório de preenchimento não foi persistido.')
  issueReport=await call('/reports/issues',adminToken)
  const currentWarnings=issueReport.issues.filter(item=>item.jobId===publication.id&&item.active)
  if(!currentWarnings.some(item=>item.category==='fields'&&item.message.includes('Cor interna'))||!currentWarnings.some(item=>item.category==='flow'))throw new Error('O relatório não separou avisos de campo e fluxo.')
  if(issueReport.issues.find(item=>item.eventId===activeExecutionError.eventId)?.active)throw new Error('O erro anterior continuou marcado como atual após uma nova tentativa.')
  let retainedQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(retainedQueue.jobs.length!==1||retainedQueue.jobs[0].jobStatus!=='awaiting_confirmation')throw new Error('O veículo saiu da extensão logo após o preenchimento.')
  await call('/publications/extension-visibility',adminToken,{method:'PATCH',body:JSON.stringify({ids:[publication.id],visible:false})})
  retainedQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  job=(await call('/publications',adminToken)).jobs.find(item=>item.id===publication.id)
  if(retainedQueue.jobs.length!==0||job.status!=='awaiting_confirmation'||job.extensionVisible!==0)throw new Error('A remoção manual da extensão alterou o histórico ou não ocultou o veículo.')
  await call('/publications/extension-visibility',adminToken,{method:'PATCH',body:JSON.stringify({ids:[publication.id],visible:true})})
  retainedQueue=await call(`/extension/queue?accountId=${first.id}`,adminToken)
  if(retainedQueue.jobs.length!==1)throw new Error('O veículo não voltou para a extensão após ser reativado no painel.')
  await expectStatus(409,()=>call(`/extension/jobs/${publication.id}/prepare`,adminToken,{method:'POST',body:JSON.stringify({accountId:first.id,instanceId:extensionOne})}))
  await expectStatus(409,()=>call(`/publications/${publication.id}`,adminToken,{method:'PATCH',body:JSON.stringify({status:'pending'})}))
  await call(`/publications/${publication.id}`,adminToken,{method:'PATCH',body:JSON.stringify({status:'pending',confirmNoPublication:true})})
  job=(await call('/publications',adminToken)).jobs.find(item=>item.id===publication.id)
  if(job.fillReport||job.errorCode)throw new Error('A repetição não limpou o diagnóstico anterior.')
  const publishedPrepared=await call(`/extension/jobs/${publication.id}/prepare`,adminToken,{method:'POST',body:JSON.stringify({accountId:first.id,instanceId:extensionOne})})
  await call(`/extension/jobs/${publication.id}/fill-result`,adminToken,{method:'PATCH',body:JSON.stringify({leaseToken:publishedPrepared.leaseToken,filledCount:15,totalCount:15,imageCount:7,missing:[],fields:[],advanced:true,selectedGroups:['Compra-se e Vende-se | https://www.facebook.com/groups/123456','Carros e Motos Criciúma e Região'],missingGroups:[],flowIssues:[],published:true,resultUrl:'https://www.facebook.com/marketplace/item/123',extensionVersion:'0.11.0'})})
  job=(await call('/publications',adminToken)).jobs.find(item=>item.id===publication.id)
  const vehicle=(await call('/vehicles',adminToken)).vehicles.find(item=>item.id===1)
  if(job.status!=='completed'||vehicle.status!=='Publicado'||!job.fillReport?.published||job.fillReport?.selectedGroups?.length!==2)throw new Error('A publicação automática não encerrou o trabalho e o veículo.')
  issueReport=await call('/reports/issues',adminToken)
  if(!issueReport.issues.some(item=>item.jobId===publication.id&&item.category==='recovery')||issueReport.issues.some(item=>item.jobId===publication.id&&item.active))throw new Error('O relatório não preservou o histórico ou deixou pendências após a conclusão.')
  const completedTimeline=await call(`/publications/${publication.id}/timeline`,adminToken)
  const completedEvents=new Set(completedTimeline.events.map(event=>event.eventType))
  for(const type of ['created','filling_started','fill_error','stalled_recovered','filled_waiting_confirmation','hidden_from_extension','shown_in_extension','retry_requested','auto_published'])if(!completedEvents.has(type))throw new Error(`O histórico da extensão não registrou o evento ${type}.`)
  if(!completedTimeline.events.some(event=>event.eventType==='filling_started'&&event.actor==='Extensão AutoFlow'))throw new Error('O histórico não diferenciou a ação automática da ação humana.')

  const photoClone=await call('/vehicles',adminToken,{method:'POST',body:JSON.stringify({year:2019,make:'Renault',model:'Sandero',trim:'Zen',price:45900,km:62000,vehicleType:'Carro/picape',location:'São Paulo, SP',transmission:'Manual',fuelType:'Flex',bodyType:'Hatch',condition:'Excelente',exteriorColor:'Prateado',interiorColor:'Preto',description:'Cadastro duplicado para validar a proteção por foto.',status:'Pronto'})})
  await call(`/vehicles/${photoClone.id}/images`,adminToken,{method:'POST',body:JSON.stringify({name:'foto-repetida.jpg',mimeType:'image/jpeg',dataBase64:Buffer.from('foto-um').toString('base64')})})
  await expectStatus(409,()=>call('/publications',adminToken,{method:'POST',body:JSON.stringify({vehicleId:photoClone.id,accountId:second.id})}))

  await call('/vehicles/1/mark-sold',adminToken,{method:'POST'})
  let soldVehicle=(await call('/vehicles',adminToken)).vehicles.find(item=>item.id===1)
  if(soldVehicle.status!=='Vendido'||!soldVehicle.soldAt||soldVehicle.pendingRemovalCount!==1)throw new Error('Marcar como vendido não registrou a data nem contou o anúncio pendente de remoção.')
  await call(`/publications/${publication.id}`,adminToken,{method:'PATCH',body:JSON.stringify({status:'removed'})})
  job=(await call('/publications',adminToken)).jobs.find(item=>item.id===publication.id)
  if(job.status!=='removed'||!job.removedAt)throw new Error('A remoção do anúncio não foi registrada.')
  soldVehicle=(await call('/vehicles',adminToken)).vehicles.find(item=>item.id===1)
  if(soldVehicle.pendingRemovalCount!==0)throw new Error('O veículo continuou marcado como pendente de remoção após confirmar a remoção do anúncio.')
  const uploadedFile=join(dataDir,'uploads',new URL(imageOne.url).pathname.split('/').pop())
  if(!existsSync(uploadedFile))throw new Error('A foto de teste não existia antes da exclusão do veículo.')
  const deletion=await call('/vehicles',adminToken,{method:'DELETE',body:JSON.stringify({ids:[1,1]})})
  if(deletion.deleted!==1||deletion.removedJobs!==1)throw new Error('A exclusão não informou corretamente o veículo e o histórico removidos.')
  if(existsSync(uploadedFile))throw new Error('O arquivo da foto permaneceu no disco após excluir o veículo.')
  if((await call('/vehicles',adminToken)).vehicles.some(item=>item.id===1))throw new Error('O veículo continuou no estoque após a exclusão.')
  if((await call('/publications',adminToken)).jobs.some(item=>item.id===publication.id))throw new Error('O trabalho de publicação continuou após excluir o veículo.')
  if((await call('/reports/issues',adminToken)).issues.some(item=>item.jobId===publication.id))throw new Error('O relatório manteve eventos órfãos após excluir o veículo.')
  await expectStatus(404,()=>call('/vehicles',adminToken,{method:'DELETE',body:JSON.stringify({ids:[1]})}))

  console.log(JSON.stringify({ok:true,profileIsolation:true,sellerIsolation:true,jobId:publication.id,preparedVehicle:prepared.vehicle.model,finalStatus:job.status,vehicleStatus:soldVehicle.status},null,2))
}finally{
  server.kill()
  await new Promise(resolve=>server.once('exit',resolve))
  await rm(dataDir,{recursive:true,force:true})
}
