import { useEffect, useMemo, useState } from 'react'
import { Car, Check, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, Clock3, Edit3, ImagePlus, MoreHorizontal, Plus, Search, Send, Tag, Trash2, X } from 'lucide-react'
import { FieldLabel, HelpTip } from './HelpTip'

type ApiFn=(path:string,options?:RequestInit)=>Promise<any>
export type VehicleRecord={id:number;year:number;make:string;model:string;trim:string;price:number;km:number;seller:string;initials:string;status:'Pronto'|'Publicado'|'Rascunho'|'Atenção'|'Vendido';color:string;updatedAt?:string;vehicleType?:string;location?:string;transmission?:string;fuelType?:string;bodyType?:string;exteriorColor?:string;description?:string;imageCount?:number;thumbnailUrl?:string;soldAt?:string;pendingRemovalCount?:number}
type ImageRecord={id:number;originalName:string;url:string;mimeType:string}
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})

function Badge({status}:{status:VehicleRecord['status']}){const icon=status==='Publicado'?<Check size={13}/>:status==='Atenção'?<CircleAlert size={13}/>:status==='Rascunho'?<Clock3 size={13}/>:status==='Vendido'?<Tag size={13}/>:<span className="dot"/>;return <span className={`badge ${status.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}`}>{icon}{status}</span>}
function Thumb({vehicle}:{vehicle:VehicleRecord}){return <div className="car-thumb" style={{background:vehicle.color}}>{vehicle.thumbnailUrl?<img src={vehicle.thumbnailUrl} alt=""/>:<Car size={30} strokeWidth={1.4}/>} {Boolean(vehicle.imageCount)&&<span className="photo-count">{vehicle.imageCount}</span>}</div>}
async function filePayload(file:File){const dataBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});return{name:file.name,mimeType:file.type,dataBase64}}

export default function VehiclesView({api,vehicles,accounts,reload,notify}:{api:ApiFn;vehicles:VehicleRecord[];accounts:{id:number;label:string}[];reload:()=>Promise<void>;notify:(message:string)=>void}){
  const[query,setQuery]=useState(''),[status,setStatus]=useState('Todos'),[selected,setSelected]=useState<Set<number>>(new Set()),[menuId,setMenuId]=useState<number|null>(null),[editor,setEditor]=useState<VehicleRecord|null|undefined>(undefined)
  const filtered=useMemo(()=>vehicles.filter(v=>`${v.make} ${v.model} ${v.year} ${v.seller}`.toLowerCase().includes(query.toLowerCase())&&(status==='Todos'||v.status===status)),[vehicles,query,status])
  const allSelected=filtered.length>0&&filtered.every(v=>selected.has(v.id))
  function toggleAll(){setSelected(allSelected?new Set():new Set(filtered.map(v=>v.id)))}
  function toggleOne(id:number){setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})}
  async function remove(ids:number[]){if(!ids.length||!window.confirm(`Excluir ${ids.length} veículo${ids.length>1?'s':''}? Fotos e publicações relacionadas também serão removidas.`))return;try{const result=await api('/vehicles',{method:'DELETE',body:JSON.stringify({ids})});setSelected(new Set());setMenuId(null);notify(`${result.deleted} veículo${result.deleted===1?'':'s'} excluído${result.deleted===1?'':'s'}.`);await reload()}catch(error){notify(error instanceof Error?error.message:'Erro ao excluir veículos')}}
  async function enqueue(vehicleId:number){
    setMenuId(null)
    if(!accounts.length)return notify('Associe um perfil do Brave em Equipe e contas antes de publicar.')
    if(accounts.length>1)return notify('Mais de um perfil associado: escolha qual vai publicar na tela Publicações.')
    try{await api('/publications',{method:'POST',body:JSON.stringify({vehicleId,accountId:accounts[0].id})});notify('Veículo adicionado à fila de publicação.');await reload()}catch(error){const missing=(error as {missing?:string[]})?.missing;notify(missing?.length?`Complete antes de publicar: ${missing.join(', ')}.`:error instanceof Error?error.message:'Erro ao adicionar à fila');if(missing?.length)await reload()}
  }
  async function markSold(vehicleId:number){setMenuId(null);try{await api(`/vehicles/${vehicleId}/mark-sold`,{method:'POST'});notify('Veículo marcado como vendido. Lembre-se de remover o anúncio do Facebook em até 24h.');await reload()}catch(error){notify(error instanceof Error?error.message:'Erro ao marcar veículo como vendido')}}
  return <section className="content vehicles-page">
    <div className="title-row"><div><h1>Veículos</h1><p>Gerencie dados, fotos e publicações do estoque.</p></div><div className="action-with-help"><button className="primary" onClick={()=>setEditor(null)}><Plus size={18}/>Adicionar veículo</button><HelpTip text="Cadastre todos os dados e as fotos antes de colocar o veículo na fila de publicação." placement="bottom"/></div></div>
    <div className="stats"><article><span className="stat-icon blue"><Car/></span><div><small>Total no estoque</small><strong>{vehicles.length}</strong><em>veículos ativos</em></div></article><article><span className="stat-icon green"><Check/></span><div><small>Publicados</small><strong>{vehicles.filter(v=>v.status==='Publicado').length}</strong><em>anúncios ativos</em></div></article><article><span className="stat-icon amber"><Clock3/></span><div><small>Na fila</small><strong>{vehicles.filter(v=>v.status==='Pronto').length}</strong><em>aguardando vendedor</em></div></article><article><span className="stat-icon red"><CircleAlert/></span><div><small>Precisam de atenção</small><strong>{vehicles.filter(v=>v.status==='Atenção').length}</strong><em>revisar dados</em></div></article></div>
    <div className="panel">
      <div className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar veículo ou vendedor..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option>Todos</option><option>Pronto</option><option>Publicado</option><option>Rascunho</option><option>Atenção</option><option>Vendido</option></select><button className="secondary">Todas as lojas<ChevronDown size={15}/></button></div>
      {selected.size>0&&<div className="bulk-bar"><div><Check/><strong>{selected.size}</strong><span>selecionado{selected.size>1?'s':''}</span></div><HelpTip tone="warning" text="A exclusão remove os veículos, suas fotos e os registros de publicação relacionados. Uma confirmação será solicitada." placement="bottom"/><button onClick={()=>remove([...selected])}><Trash2/>Excluir selecionados</button><button className="bulk-clear" onClick={()=>setSelected(new Set())}><X/>Limpar</button></div>}
      <div className="table-wrap"><table><thead><tr><th className="check-cell"><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Selecionar todos os veículos"/></th><th>VEÍCULO</th><th>PREÇO</th><th>QUILOMETRAGEM</th><th>RESPONSÁVEL</th><th>STATUS</th><th>FOTOS</th><th>ATUALIZADO</th><th/></tr></thead><tbody>{filtered.map(v=><tr key={v.id} className={selected.has(v.id)?'selected-row':''}><td className="check-cell"><input type="checkbox" checked={selected.has(v.id)} onChange={()=>toggleOne(v.id)} aria-label={`Selecionar ${v.year} ${v.make} ${v.model}`}/></td><td><div className="vehicle"><Thumb vehicle={v}/><div><strong>{v.year} {v.make} {v.model}</strong><small>{v.trim}</small></div></div></td><td><strong>{money.format(v.price)}</strong></td><td>{v.km.toLocaleString('pt-BR')} km</td><td><div className="seller"><span>{v.initials}</span>{v.seller}</div></td><td><Badge status={v.status}/></td><td><span className={`image-status ${v.imageCount?'has-images':''}`}>{v.imageCount||0}/20</span></td><td className="muted">{v.updatedAt?new Date(v.updatedAt+'Z').toLocaleDateString('pt-BR'):'agora'}</td><td className="actions-cell"><button className="row-more" onClick={()=>setMenuId(menuId===v.id?null:v.id)} aria-label={`Ações de ${v.year} ${v.make} ${v.model}`} aria-expanded={menuId===v.id}><MoreHorizontal/></button>{menuId===v.id&&<div className="row-menu"><button onClick={()=>{setEditor(v);setMenuId(null)}}><Edit3/>Editar e gerenciar fotos</button><button onClick={()=>enqueue(v.id)}><Send/>Adicionar à fila<HelpTip text="Cria uma tarefa para o perfil escolhido. A extensão preenche o anúncio; o clique final em Publicar continua manual." placement="bottom"/></button>{v.status!=='Vendido'&&<button onClick={()=>markSold(v.id)}><Tag/>Marcar como vendido<HelpTip tone="warning" text="A Meta exige remover o anúncio do Facebook em até 24h após a venda. O AutoFlow vai lembrar você." placement="bottom"/></button>}<button className="danger" onClick={()=>remove([v.id])}><Trash2/>Excluir veículo<HelpTip tone="warning" text="Também remove fotos e históricos de publicação deste veículo." placement="bottom"/></button></div>}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">Nenhum veículo encontrado.</div>}</div>
      <footer className="panel-foot"><span>Mostrando {filtered.length} de {vehicles.length} veículos</span><div><button disabled>Anterior</button><button className="page">1</button><button>Próximo</button></div></footer>
    </div>
    {editor!==undefined&&<VehicleDrawer api={api} vehicle={editor} onClose={()=>setEditor(undefined)} onSaved={async message=>{setEditor(undefined);notify(message);await reload()}}/>}
  </section>
}

function VehicleDrawer({api,vehicle,onClose,onSaved}:{api:ApiFn;vehicle:VehicleRecord|null;onClose:()=>void;onSaved:(message:string)=>Promise<void>}){
  const[images,setImages]=useState<ImageRecord[]>([]),[files,setFiles]=useState<File[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState('')
  useEffect(()=>{if(vehicle)api(`/vehicles/${vehicle.id}/images`).then(data=>setImages(data.images)).catch(()=>setImages([]))},[vehicle?.id])
  async function upload(vehicleId:number){for(const file of files.slice(0,20-images.length)){await api(`/vehicles/${vehicleId}/images`,{method:'POST',body:JSON.stringify(await filePayload(file))})}}
  async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget);const payload={year:Number(f.get('year')),make:f.get('make'),model:f.get('model'),trim:f.get('trim'),price:Number(f.get('price')),km:Number(f.get('km')),vehicleType:f.get('vehicleType'),location:f.get('location'),transmission:f.get('transmission'),fuelType:f.get('fuelType'),bodyType:f.get('bodyType'),exteriorColor:f.get('exteriorColor'),description:f.get('description'),status:f.get('status')};try{let id=vehicle?.id;if(id)await api(`/vehicles/${id}`,{method:'PATCH',body:JSON.stringify(payload)});else{id=(await api('/vehicles',{method:'POST',body:JSON.stringify(payload)})).id}await upload(id!);await onSaved(vehicle?'Veículo atualizado com sucesso.':'Veículo adicionado ao estoque.')}catch(err){setError(err instanceof Error?err.message:'Erro ao salvar veículo');setSaving(false)}}
  async function removeImage(image:ImageRecord){await api(`/vehicle-images/${image.id}`,{method:'DELETE'});setImages(current=>current.filter(item=>item.id!==image.id))}
  async function moveImage(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=images.length||!vehicle)return;const next=[...images];[next[index],next[target]]=[next[target],next[index]];const previous=images;setImages(next);try{await api(`/vehicles/${vehicle.id}/images/reorder`,{method:'PATCH',body:JSON.stringify({order:next.map(item=>item.id)})})}catch(err){setImages(previous);setError(err instanceof Error?err.message:'Erro ao reordenar fotos')}}
  return <div className="overlay" onMouseDown={onClose}><aside className="drawer vehicle-drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X/></button><span className="eyebrow">{vehicle?'EDITAR ESTOQUE':'NOVO REGISTRO'}</span><h2>{vehicle?'Editar veículo':'Adicionar veículo'}</h2><p>Preencha os dados usados pelo Marketplace e adicione até 20 fotos.</p>{error&&<div className="auth-error"><CircleAlert/>{error}</div>}<form onSubmit={submit}>
    <div className="drawer-section"><h3>Identificação</h3><div className="vehicle-form-grid"><label><FieldLabel help="Define a categoria inicial do formulário do Marketplace. Use a opção que corresponde ao documento do veículo.">Tipo de veículo</FieldLabel><select name="vehicleType" defaultValue={vehicle?.vehicleType||'Carro/Caminhonete'}><option>Carro/Caminhonete</option><option>Motocicleta</option><option>Outro veículo</option></select></label><label><FieldLabel help="Ano/modelo anunciado. Confira com o documento para evitar divergências.">Ano</FieldLabel><input name="year" type="number" min="1900" max="2100" defaultValue={vehicle?.year||2024} required/></label><label><FieldLabel help="Nome da montadora como aparece na lista do Marketplace, por exemplo Toyota.">Fabricante</FieldLabel><input name="make" defaultValue={vehicle?.make||''} placeholder="Toyota" required/></label><label><FieldLabel help="Modelo sem repetir fabricante ou ano, por exemplo Corolla.">Modelo</FieldLabel><input name="model" defaultValue={vehicle?.model||''} placeholder="Corolla" required/></label><label><FieldLabel help="Versão ou acabamento, por exemplo XEi 2.0. Esse dado ajuda a diferenciar o anúncio.">Versão</FieldLabel><input name="trim" defaultValue={vehicle?.trim||''} placeholder="XEi 2.0"/></label><label><FieldLabel help="Cidade usada no anúncio. O Facebook pode pedir que você confirme uma sugestão após o preenchimento.">Localização</FieldLabel><input name="location" defaultValue={vehicle?.location||''} placeholder="Criciúma, SC" required/></label></div></div>
    <div className="drawer-section"><h3>Detalhes</h3><div className="vehicle-form-grid"><label><FieldLabel help="Valor total anunciado, sem pontos ou símbolo de moeda. Exemplo: 119900.">Preço</FieldLabel><input name="price" type="number" min="0" defaultValue={vehicle?.price||0} required/></label><label><FieldLabel help="Quilometragem atual em números inteiros. Exemplo: 42500.">Quilometragem</FieldLabel><input name="km" type="number" min="0" defaultValue={vehicle?.km||0} required/></label><label><FieldLabel help="Selecione a opção equivalente no Marketplace; nomes diferentes podem impedir o preenchimento.">Câmbio</FieldLabel><select name="transmission" defaultValue={vehicle?.transmission||'Automático'}><option>Automático</option><option>Manual</option><option>Automatizado</option></select></label><label><FieldLabel help="Informe o combustível principal aceito pelo veículo.">Combustível</FieldLabel><select name="fuelType" defaultValue={vehicle?.fuelType||'Flex'}><option>Flex</option><option>Gasolina</option><option>Diesel</option><option>Elétrico</option><option>Híbrido</option></select></label><label><FieldLabel help="Formato da carroceria. Deve corresponder a uma opção disponível no formulário do Facebook.">Carroceria</FieldLabel><select name="bodyType" defaultValue={vehicle?.bodyType||'Sedã'}><option>Sedã</option><option>SUV</option><option>Hatch</option><option>Picape</option><option>Van</option><option>Cupê</option></select></label><label><FieldLabel help="Cor predominante externa, sem incluir acabamento interno.">Cor externa</FieldLabel><input name="exteriorColor" defaultValue={vehicle?.exteriorColor||''} placeholder="Prata"/></label><label><FieldLabel help="Rascunho: incompleto. Pronto: disponível na extensão. Publicado: anúncio confirmado. Atenção: precisa de revisão. Vendido: use o menu de ações para registrar a data da venda.">Status</FieldLabel><select name="status" defaultValue={vehicle?.status||'Rascunho'}><option>Rascunho</option><option>Pronto</option><option>Publicado</option><option>Atenção</option><option>Vendido</option></select></label></div><label><FieldLabel help="Inclua conservação, opcionais e condições reais. Evite promessas ou informações que não possam ser verificadas.">Descrição</FieldLabel><textarea name="description" rows={5} defaultValue={vehicle?.description||''} placeholder="Descreva conservação, opcionais e condições..."/></label></div>
    <div className="drawer-section"><h3 className="section-title-help">Fotos <span>{images.length+files.length}/20</span><HelpTip text="A primeira foto vira a capa. Use as setas para reordenar; a extensão envia no máximo 20 na ordem cadastrada."/></h3>{images.length>0&&<div className="image-grid">{images.map((image,index)=><div key={image.id}>{index===0&&<span className="cover-badge">Capa</span>}<img src={image.url} alt={image.originalName}/><button type="button" onClick={()=>removeImage(image)} aria-label={`Excluir ${image.originalName}`}><X/></button><div className="move-controls"><button type="button" disabled={index===0} onClick={()=>moveImage(index,-1)} aria-label={`Mover ${image.originalName} para a esquerda`}><ChevronLeft/></button><button type="button" disabled={index===images.length-1} onClick={()=>moveImage(index,1)} aria-label={`Mover ${image.originalName} para a direita`}><ChevronRight/></button></div></div>)}</div>}<label className="image-upload"><ImagePlus/><strong>Adicionar fotos</strong><span>JPG, PNG ou WebP · até 12 MB cada</span><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>setFiles([...e.target.files||[]].slice(0,20-images.length))}/></label>{files.length>0&&<div className="pending-files">{files.map(file=><span key={file.name}>{file.name}</span>)}</div>}</div>
    <button className="primary save-vehicle" disabled={saving}>{saving?'Salvando...':vehicle?'Salvar alterações':'Adicionar ao estoque'}</button></form></aside></div>
}
