import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Car, Check, CircleAlert, Clock3, ExternalLink, Laptop, Moon, Palette, Plus, RotateCcw, Save, Send, Settings, ShieldCheck, Sun, Users, X } from 'lucide-react'
import { FieldLabel, HelpTip } from './HelpTip'

type ApiFn = (path:string, options?:RequestInit) => Promise<any>
type Vehicle = {id:number;year:number;make:string;model:string;price:number;km:number;status:string;seller:string}
type FillReport={filledCount:number;totalCount:number;imageCount:number;missing:string[];fields:Array<{name:string;ok:boolean}>}
type Job = {id:number;status:string;vehicleId:number;year:number;make:string;model:string;price:number;accountLabel:string;seller:string;createdAt:string;resultUrl?:string;errorCode?:string;extensionVersion?:string;fillReport?:FillReport|null}
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})

export function OverviewView({api,vehicles,navigate}:{api:ApiFn;vehicles:Vehicle[];navigate:(page:string)=>void}) {
  const [data,setData]=useState<any>(null)
  useEffect(()=>{api('/overview').then(setData)},[])
  const stats=data?.vehicleStats||{}
  return <section className="content">
    <div className="title-row"><div><span className="page-kicker">PAINEL OPERACIONAL</span><h1>Visão geral</h1><p>Acompanhe o estoque e mantenha a equipe em movimento.</p></div><button className="primary" onClick={()=>navigate('Publicações')}><Send size={18}/>Abrir fila</button></div>
    <div className="hero-card"><div><span>Valor estimado do estoque</span><strong>{money.format(Number(stats.inventoryValue||0))}</strong><p>{stats.total||vehicles.length} veículos ativos na operação</p></div><div className="hero-score"><strong>{stats.total?Math.round((Number(stats.published||0)/Number(stats.total))*100):0}%</strong><span>do estoque publicado</span></div></div>
    <div className="stats overview-stats">
      <article><span className="stat-icon blue"><Car/></span><div><small>Estoque ativo</small><strong>{stats.total??vehicles.length}</strong><em>veículos</em></div></article>
      <article><span className="stat-icon green"><Check/></span><div><small>Publicados</small><strong>{stats.published||0}</strong><em>anúncios ativos</em></div></article>
      <article><span className="stat-icon amber"><Clock3/></span><div><small>Prontos para fila</small><strong>{stats.ready||0}</strong><em>aguardando ação</em></div></article>
      <article><span className="stat-icon red"><CircleAlert/></span><div><small>Pendências</small><strong>{stats.attention||0}</strong><em>requer revisão</em></div></article>
    </div>
    <div className="overview-grid"><article className="module-card"><div className="module-head"><div><h2>Estoque recente</h2><span>Últimos veículos atualizados</span></div><button onClick={()=>navigate('Veículos')}>Ver todos</button></div><div className="compact-list">{vehicles.slice(0,4).map(v=><div key={v.id}><span className="mini-car"><Car/></span><div><strong>{v.year} {v.make} {v.model}</strong><small>{money.format(v.price)} · {v.seller}</small></div><span className={`simple-status ${v.status.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}`}>{v.status}</span></div>)}</div></article>
      <article className="module-card quick-card"><div className="module-head"><div><h2>Ações rápidas</h2><span>Atalhos da operação</span></div></div><button onClick={()=>navigate('Veículos')}><Car/><div><strong>Gerenciar estoque</strong><small>Cadastre e revise veículos</small></div><ExternalLink/></button><button onClick={()=>navigate('Publicações')}><Send/><div><strong>Preparar publicações</strong><small>Distribua veículos por perfil</small></div><ExternalLink/></button><button onClick={()=>navigate('Equipe e contas')}><Users/><div><strong>Equipe e contas</strong><small>Gerencie acessos e perfis</small></div><ExternalLink/></button></article></div>
  </section>
}

export function PublicationsView({api,vehicles}:{api:ApiFn;vehicles:Vehicle[]}) {
  const [jobs,setJobs]=useState<Job[]>([]),[accounts,setAccounts]=useState<any[]>([]),[open,setOpen]=useState(false),[message,setMessage]=useState('')
  const load=()=>Promise.all([api('/publications'),api('/team')]).then(([p,t])=>{setJobs(p.jobs);setAccounts(t.accounts)})
  useEffect(()=>{load()},[])
  async function enqueue(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/publications',{method:'POST',body:JSON.stringify({vehicleId:Number(f.get('vehicleId')),accountId:f.get('accountId')?Number(f.get('accountId')):null})});setOpen(false);setMessage('Veículo adicionado à fila.');await load()}catch(err){setMessage(err instanceof Error?err.message:'Erro ao criar publicação')}}
  async function update(id:number,status:string){await api(`/publications/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load()}
  const pending=jobs.filter(j=>['pending','filling','awaiting_confirmation'].includes(j.status)).length,completed=jobs.filter(j=>j.status==='completed').length,errors=jobs.filter(j=>j.status==='error').length
  return <section className="content"><div className="title-row"><div><span className="page-kicker">CONTROLE DE SAÍDA</span><h1>Publicações</h1><p>Organize o que cada perfil deve publicar no Brave.</p></div><div className="action-with-help"><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Adicionar à fila</button><HelpTip text="A fila distribui um veículo para um perfil local do Brave. Ela não publica o anúncio automaticamente." placement="bottom"/></div></div>
    {message&&<div className="inline-message">{message}<button onClick={()=>setMessage('')}><X/></button></div>}
    <div className="stats"><article><span className="stat-icon amber"><Clock3/></span><div><small>Pendentes</small><strong>{pending}</strong><em>na fila</em></div></article><article><span className="stat-icon green"><Check/></span><div><small>Concluídas</small><strong>{completed}</strong><em>confirmadas</em></div></article><article><span className="stat-icon red"><CircleAlert/></span><div><small>Com erro</small><strong>{errors}</strong><em>requer atenção</em></div></article><article><span className="stat-icon blue"><Laptop/></span><div><small>Perfis locais</small><strong>{accounts.length}</strong><em>associados</em></div></article></div>
    <div className="panel"><div className="pub-tabs"><strong>Todas</strong><span>{jobs.length} registros</span><button onClick={()=>load()}><RotateCcw size={15}/>Atualizar</button></div><div className="table-wrap"><table><thead><tr><th>VEÍCULO</th><th>RESPONSÁVEL</th><th>PERFIL</th><th>STATUS</th><th>CRIADO</th><th>AÇÕES</th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td><strong>{j.year} {j.make} {j.model}</strong><small className="table-sub">{money.format(j.price)} · trabalho #{j.id}</small></td><td>{j.seller}</td><td>{j.accountLabel}</td><td><div className="job-status-cell"><JobBadge status={j.status}/><JobReport job={j}/></div></td><td className="muted">{new Date(j.createdAt+'Z').toLocaleDateString('pt-BR')}</td><td><div className="job-actions">{j.status==='awaiting_confirmation'&&<><button onClick={()=>update(j.id,'completed')}><Check/>Confirmar publicado</button><button onClick={()=>update(j.id,'pending')}><RotateCcw/>Preencher novamente</button></>}{j.status==='error'&&<button onClick={()=>update(j.id,'pending')}><RotateCcw/>Tentar novamente</button>}{['pending','filling','error'].includes(j.status)&&<button className="danger-link" onClick={()=>update(j.id,'canceled')}><X/>Cancelar</button>}</div></td></tr>)}</tbody></table>{!jobs.length&&<div className="empty">A fila ainda está vazia. Adicione o primeiro veículo.</div>}</div></div>
    {open&&<div className="overlay" onMouseDown={()=>setOpen(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}><X/></button><span className="eyebrow">NOVA PUBLICAÇÃO</span><h2>Adicionar à fila</h2><p>Escolha o veículo e o perfil local. A extensão continuará exigindo confirmação antes de publicar.</p><form onSubmit={enqueue}><label><FieldLabel help="Somente veículos ainda não marcados como Publicado aparecem nesta lista.">Veículo</FieldLabel><select name="vehicleId" required><option value="">Selecione</option>{vehicles.filter(v=>v.status!=='Publicado').map(v=><option key={v.id} value={v.id}>{v.year} {v.make} {v.model}</option>)}</select></label><label><FieldLabel help="Cada perfil representa uma sessão local separada do Brave. O trabalho aparecerá somente quando este perfil estiver selecionado na extensão.">Perfil do Brave</FieldLabel><select name="accountId" required><option value="">Selecione o perfil responsável</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><div className="drawer-submit-help"><HelpTip tone="warning" text="Revise fotos, preço e campos preenchidos na página do Facebook antes de confirmar Publicar."/><button className="primary">Adicionar à fila</button></div></form></aside></div>}
  </section>
}
function JobBadge({status}:{status:string}){const labels:Record<string,string>={pending:'Pendente',filling:'Preenchendo',awaiting_confirmation:'Aguardando confirmação',completed:'Concluída',error:'Erro',canceled:'Cancelada'};return <span className={`job-badge ${status}`}>{labels[status]||status}</span>}
function JobReport({job}:{job:Job}){if(job.fillReport)return <small className={job.fillReport.missing.length?'job-report warning':'job-report'} title={job.fillReport.missing.length?`Revisar: ${job.fillReport.missing.join(', ')}`:'Todos os campos encontrados'}>{job.fillReport.filledCount}/{job.fillReport.totalCount} campos · {job.fillReport.imageCount} fotos{job.extensionVersion?` · ext. ${job.extensionVersion}`:''}</small>;if(job.errorCode)return <small className="job-report error">{job.errorCode}</small>;return null}

export function ReportsView({api,vehicles}:{api:ApiFn;vehicles:Vehicle[]}) {
  const [overview,setOverview]=useState<any>(null),[jobs,setJobs]=useState<Job[]>([])
  useEffect(()=>{Promise.all([api('/overview'),api('/publications')]).then(([o,p])=>{setOverview(o);setJobs(p.jobs)})},[])
  const byStatus=useMemo(()=>['Publicado','Pronto','Rascunho','Atenção'].map(status=>({status,count:vehicles.filter(v=>v.status===status).length})),[vehicles]);const max=Math.max(1,...byStatus.map(x=>x.count));const total=vehicles.length;const completed=jobs.filter(j=>j.status==='completed').length
  return <section className="content"><div className="title-row"><div><span className="page-kicker">DESEMPENHO</span><h1>Relatórios</h1><p>Indicadores consolidados do estoque e das publicações.</p></div><button className="secondary" onClick={()=>window.print()}><BarChart3 size={17}/>Imprimir relatório</button></div>
    <div className="report-kpis"><article><span>Valor em estoque</span><strong>{money.format(Number(overview?.vehicleStats?.inventoryValue||0))}</strong><small>{total} veículos cadastrados</small></article><article><span>Taxa publicada</span><strong>{total?Math.round((vehicles.filter(v=>v.status==='Publicado').length/total)*100):0}%</strong><small>do estoque atual</small></article><article><span>Publicações concluídas</span><strong>{completed}</strong><small>{jobs.length} movimentações</small></article></div>
    <div className="report-grid"><article className="module-card"><div className="module-head"><div><h2>Distribuição do estoque</h2><span>Veículos por situação</span></div></div><div className="bars">{byStatus.map(item=><div key={item.status}><div><span>{item.status}</span><strong>{item.count}</strong></div><i><b style={{width:`${item.count/max*100}%`}}/></i></div>)}</div></article><article className="module-card"><div className="module-head"><div><h2>Saúde operacional</h2><span>Leitura rápida</span></div></div><div className="health"><div className="health-ring"><strong>{total?Math.round(((total-vehicles.filter(v=>v.status==='Atenção').length)/total)*100):100}%</strong><span>saudável</span></div><ul><li><i className="green-dot"/> {vehicles.filter(v=>v.status!=='Atenção').length} veículos sem pendência</li><li><i className="red-dot"/> {vehicles.filter(v=>v.status==='Atenção').length} precisam de atenção</li><li><i className="amber-dot"/> {jobs.filter(j=>j.status==='pending').length} publicações aguardando</li></ul></div></article></div>
  </section>
}

export function SettingsView({api,onSaved,theme,onThemeChange}:{api:ApiFn;onSaved:()=>void;theme:'light'|'dark';onThemeChange:(theme:'light'|'dark')=>void}) {
  const [data,setData]=useState<any>(null),[message,setMessage]=useState('')
  useEffect(()=>{api('/settings').then(setData)},[])
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/settings',{method:'PATCH',body:JSON.stringify({organizationName:f.get('organizationName'),defaultLocation:f.get('defaultLocation'),dailyLimit:Number(f.get('dailyLimit')),requireConfirmation:f.get('requireConfirmation')==='on',descriptionTemplate:f.get('descriptionTemplate')})});setMessage('Configurações salvas com sucesso.');onSaved()}catch(err){setMessage(err instanceof Error?err.message:'Erro ao salvar')}}
  if(!data)return <section className="content"><div className="empty">Carregando configurações...</div></section>
  return <section className="content settings-page"><div className="title-row"><div><span className="page-kicker">ADMINISTRAÇÃO</span><h1>Configurações</h1><p>Personalize a empresa e os controles de publicação.</p></div></div>{message&&<div className="inline-message success">{message}<button onClick={()=>setMessage('')}><X/></button></div>}
    <form onSubmit={save}><article className="settings-card"><div className="settings-icon"><Settings/></div><div className="settings-content"><h2>Dados da empresa</h2><p>Identificação exibida para todos os usuários.</p><div className="settings-fields"><label><FieldLabel help="Nome exibido no painel para todos os integrantes desta organização.">Nome da empresa</FieldLabel><input name="organizationName" defaultValue={data.organization.name} required/></label><label><FieldLabel help="Valor sugerido nos novos veículos; pode ser alterado em cada cadastro.">Localização padrão</FieldLabel><input name="defaultLocation" defaultValue={data.settings.defaultLocation}/></label></div></div></article>
      <article className="settings-card"><div className="settings-icon"><Send/></div><div className="settings-content"><h2>Regras de publicação</h2><p>Limites operacionais usados pelo painel e pela extensão.</p><div className="settings-fields"><label><FieldLabel help="Limite operacional interno por perfil. Use um valor compatível com a rotina da equipe e revise qualquer alerta do Facebook.">Limite diário por perfil</FieldLabel><input name="dailyLimit" type="number" min="1" max="50" defaultValue={data.settings.dailyLimit}/><small>Entre 1 e 50 publicações</small></label><label className="toggle-label"><span><span className="field-label"><strong>Exigir confirmação manual</strong><HelpTip tone="warning" text="Recomendado: o preenchimento pode ser assistido, mas a pessoa deve revisar e clicar em Publicar."/></span><small>A extensão nunca pressionará Publicar sozinha</small></span><input name="requireConfirmation" type="checkbox" defaultChecked={Boolean(data.settings.requireConfirmation)}/></label></div><label><FieldLabel help="Texto-base aplicado à descrição. As variáveis entre chaves são substituídas pelos dados do veículo.">Modelo de descrição</FieldLabel><textarea name="descriptionTemplate" rows={4} defaultValue={data.settings.descriptionTemplate}/><small>Variáveis disponíveis: {'{ano} {marca} {modelo} {versao} {km}'}</small></label></div></article>
      <article className="settings-card"><div className="settings-icon"><Palette/></div><div className="settings-content"><h2>Aparência</h2><p>O tema é salvo somente neste navegador.</p><div className="theme-options"><button type="button" className={theme==='light'?'selected':''} onClick={()=>onThemeChange('light')}><span><Sun/></span><div><strong>Tema claro</strong><small>Maior luminosidade</small></div><Check/></button><button type="button" className={theme==='dark'?'selected':''} onClick={()=>onThemeChange('dark')}><span><Moon/></span><div><strong>Tema escuro</strong><small>Conforto em ambientes escuros</small></div><Check/></button></div></div></article>
      <article className="settings-card security-settings"><div className="settings-icon"><ShieldCheck/></div><div className="settings-content"><h2>Segurança das contas</h2><p>Credenciais do Facebook não são aceitas nem armazenadas. Cada sessão permanece no perfil local do Brave utilizado pelo vendedor.</p><div className="policy-row"><Check/><span>Cookies e senhas fora do servidor</span></div><div className="policy-row"><Check/><span>Confirmação humana antes da publicação</span></div></div></article><div className="settings-save"><button className="primary"><Save size={17}/>Salvar configurações</button></div></form>
  </section>
}
