import { useEffect, useMemo, useState } from 'react'
import { BarChart3, Camera, Car, Check, CircleAlert, Clock3, Eye, EyeOff, ExternalLink, Filter, Laptop, Moon, Palette, Plus, RotateCcw, Save, Send, Settings, ShieldCheck, Sun, TrendingUp, Users, WalletCards, X } from 'lucide-react'
import { FieldLabel, HelpTip } from './HelpTip'

type ApiFn = (path:string, options?:RequestInit) => Promise<any>
type Vehicle = {id:number;year:number;make:string;model:string;price:number;km:number;status:string;seller:string;imageCount?:number;updatedAt?:string}
type FillReport={filledCount:number;totalCount:number;imageCount:number;missing:string[];fields:Array<{name:string;ok:boolean}>;advanced?:boolean;selectedGroups?:string[];missingGroups?:string[];published?:boolean}
type Job = {id:number;status:string;vehicleId:number;year:number;make:string;model:string;price:number;accountLabel:string;seller:string;createdAt:string;resultUrl?:string;errorCode?:string;extensionVersion?:string;extensionVisible?:number;fillReport?:FillReport|null;removedAt?:string}
const money = new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})

export function OverviewView({api,vehicles,navigate}:{api:ApiFn;vehicles:Vehicle[];navigate:(page:string)=>void}) {
  const [data,setData]=useState<any>(null)
  useEffect(()=>{api('/overview').then(setData)},[])
  const stats=data?.vehicleStats||{}
  return <section className="content">
    <div className="title-row"><div><span className="page-kicker">PAINEL OPERACIONAL</span><h1>Visão geral</h1><p>Acompanhe o estoque e mantenha a equipe em movimento.</p></div><button className="primary" onClick={()=>navigate('Publicações')}><Send size={18}/>Abrir fila</button></div>
    <div className="hero-card"><div><span>Valor estimado do estoque</span><strong>{money.format(Number(stats.inventoryValue||0))}</strong><p>{stats.total||vehicles.length} veículos ativos na operação</p></div><div className="hero-score"><strong>{stats.total?Math.round((Number(stats.published||0)/Number(stats.total))*100):0}%</strong><span>do estoque publicado</span></div></div>
    <div className="stats overview-stats">
      <article><span className="stat-icon blue"><Car/></span><div><small>Estoque ativo</small><strong>{stats.total??vehicles.length}</strong><em>veículos</em></div></article>
      <article><span className="stat-icon green"><Check/></span><div><small>Publicados</small><strong>{stats.published||0}</strong><em>anúncios ativos</em></div></article>
      <article><span className="stat-icon amber"><Clock3/></span><div><small>Prontos para fila</small><strong>{stats.ready||0}</strong><em>aguardando ação</em></div></article>
      <article><span className="stat-icon red"><CircleAlert/></span><div><small>Pendências</small><strong>{stats.attention||0}</strong><em>requer revisão</em></div></article>
    </div>
    <div className="overview-grid"><article className="module-card"><div className="module-head"><div><h2>Estoque recente</h2><span>Últimos veículos atualizados</span></div><button onClick={()=>navigate('Veículos')}>Ver todos</button></div><div className="compact-list">{vehicles.slice(0,4).map(v=><div key={v.id}><span className="mini-car"><Car/></span><div><strong>{v.year} {v.make} {v.model}</strong><small>{money.format(v.price)} · {v.seller}</small></div><span className={`simple-status ${v.status.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}`}>{v.status}</span></div>)}</div></article>
      <article className="module-card quick-card"><div className="module-head"><div><h2>Ações rápidas</h2><span>Atalhos da operação</span></div></div><button onClick={()=>navigate('Veículos')}><Car/><div><strong>Gerenciar estoque</strong><small>Cadastre e revise veículos</small></div><ExternalLink/></button><button onClick={()=>navigate('Publicações')}><Send/><div><strong>Preparar publicações</strong><small>Distribua veículos por perfil</small></div><ExternalLink/></button><button onClick={()=>navigate('Equipe e contas')}><Users/><div><strong>Equipe e contas</strong><small>Gerencie acessos e perfis</small></div><ExternalLink/></button></article></div>
  </section>
}

export function PublicationsView({api,vehicles,reload}:{api:ApiFn;vehicles:Vehicle[];reload:()=>Promise<void>}) {
  const [jobs,setJobs]=useState<Job[]>([]),[accounts,setAccounts]=useState<any[]>([]),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState<Set<number>>(new Set())
  const load=()=>Promise.all([api('/publications'),api('/team')]).then(([p,t])=>{
    setJobs(p.jobs)
    setAccounts(t.accounts)
    setSelected(current=>new Set([...current].filter(id=>p.jobs.some((job:Job)=>job.id===id&&job.extensionVisible!==0))))
  })
  useEffect(()=>{load()},[])
  async function enqueue(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/publications',{method:'POST',body:JSON.stringify({vehicleId:Number(f.get('vehicleId')),accountId:f.get('accountId')?Number(f.get('accountId')):null})});setOpen(false);setMessage('Veículo adicionado à fila.');await load();await reload()}catch(err){const missing=(err as {missing?:string[]})?.missing;setMessage(missing?.length?`Complete antes de publicar: ${missing.join(', ')}.`:err instanceof Error?err.message:'Erro ao criar publicação')}}
  async function update(id:number,status:string){await api(`/publications/${id}`,{method:'PATCH',body:JSON.stringify({status})});await load();await reload()}
  async function changeExtensionVisibility(ids:number[],visible:boolean){if(!ids.length)return;try{await api('/publications/extension-visibility',{method:'PATCH',body:JSON.stringify({ids,visible})});setSelected(new Set());setMessage(visible?`${ids.length} veículo${ids.length===1?'':'s'} devolvido${ids.length===1?'':'s'} à extensão.`:`${ids.length} veículo${ids.length===1?'':'s'} removido${ids.length===1?'':'s'} da extensão.`);await load()}catch(err){setMessage(err instanceof Error?err.message:'Erro ao atualizar a fila da extensão')}}
  function toggleSelected(id:number){setSelected(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next})}
  const extensionStatuses=['pending','filling','error','awaiting_confirmation']
  const extensionJobs=jobs.filter(job=>extensionStatuses.includes(job.status)&&job.extensionVisible!==0)
  const allExtensionSelected=extensionJobs.length>0&&extensionJobs.every(job=>selected.has(job.id))
  const pending=jobs.filter(j=>['pending','filling','awaiting_confirmation'].includes(j.status)).length,completed=jobs.filter(j=>['completed','removed'].includes(j.status)).length,errors=jobs.filter(j=>j.status==='error').length
  return <section className="content"><div className="title-row"><div><span className="page-kicker">CONTROLE DE SAÍDA</span><h1>Publicações</h1><p>Organize o que cada perfil deve publicar no Brave.</p></div><div className="action-with-help"><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Adicionar à fila</button><HelpTip text="A fila distribui um veículo para um perfil local do Brave e respeita o fluxo definido em Configurações." placement="bottom"/></div></div>
    {message&&<div className="inline-message">{message}<button onClick={()=>setMessage('')}><X/></button></div>}
    <div className="stats"><article><span className="stat-icon amber"><Clock3/></span><div><small>Pendentes</small><strong>{pending}</strong><em>na fila</em></div></article><article><span className="stat-icon green"><Check/></span><div><small>Concluídas</small><strong>{completed}</strong><em>confirmadas</em></div></article><article><span className="stat-icon red"><CircleAlert/></span><div><small>Com erro</small><strong>{errors}</strong><em>requer atenção</em></div></article><article><span className="stat-icon blue"><Laptop/></span><div><small>Perfis locais</small><strong>{accounts.length}</strong><em>associados</em></div></article></div>
    <div className="panel"><div className="pub-tabs"><strong>Todas</strong><span>{jobs.length} registros</span><small>{extensionJobs.length} na extensão</small><button onClick={()=>load()}><RotateCcw size={15}/>Atualizar</button></div>{selected.size>0&&<div className="bulk-bar"><div><Check/><strong>{selected.size}</strong><span>selecionado{selected.size===1?'':'s'}</span></div><HelpTip text="Remove somente da lista da extensão. O histórico e o relatório de preenchimento continuam no painel." placement="bottom"/><button onClick={()=>changeExtensionVisibility([...selected],false)}><EyeOff/>Remover selecionados da extensão</button><button className="bulk-clear" onClick={()=>setSelected(new Set())}><X/>Limpar</button></div>}<div className="table-wrap"><table><thead><tr><th className="check-cell"><input type="checkbox" checked={allExtensionSelected} disabled={!extensionJobs.length} onChange={()=>setSelected(allExtensionSelected?new Set():new Set(extensionJobs.map(job=>job.id)))} aria-label="Selecionar todos que estão na extensão"/></th><th>VEÍCULO</th><th>RESPONSÁVEL</th><th>PERFIL</th><th>STATUS</th><th>CRIADO</th><th>AÇÕES</th></tr></thead><tbody>{jobs.map(j=>{const active=extensionStatuses.includes(j.status),visible=j.extensionVisible!==0;return <tr key={j.id} className={selected.has(j.id)?'selected-row':''}><td className="check-cell"><input type="checkbox" checked={selected.has(j.id)} disabled={!active||!visible} onChange={()=>toggleSelected(j.id)} aria-label={`Selecionar ${j.year} ${j.make} ${j.model} na fila`}/></td><td><strong>{j.year} {j.make} {j.model}</strong><small className="table-sub">{money.format(j.price)} · trabalho #{j.id}</small></td><td>{j.seller}</td><td>{j.accountLabel}<small className={`extension-presence ${active&&visible?'visible':'hidden'}`}>{active&&visible?<><Eye/>Na extensão</>:active?<><EyeOff/>Fora da extensão</>:null}</small></td><td><div className="job-status-cell"><JobBadge status={j.status}/><JobReport job={j}/></div></td><td className="muted">{new Date(j.createdAt+'Z').toLocaleDateString('pt-BR')}</td><td><div className="job-actions">{j.status==='awaiting_confirmation'&&<><button onClick={()=>update(j.id,'completed')}><Check/>Confirmar publicado</button><button onClick={()=>update(j.id,'pending')}><RotateCcw/>Preencher novamente</button></>}{j.status==='completed'&&<button onClick={()=>update(j.id,'removed')}><X/>Marcar anúncio removido</button>}{j.status==='error'&&<button onClick={()=>update(j.id,'pending')}><RotateCcw/>Tentar novamente</button>}{active&&visible&&<button className="danger-link" onClick={()=>changeExtensionVisibility([j.id],false)}><EyeOff/>Remover da extensão</button>}{active&&!visible&&<button onClick={()=>changeExtensionVisibility([j.id],true)}><Eye/>Mostrar na extensão</button>}</div></td></tr>})}</tbody></table>{!jobs.length&&<div className="empty">A fila ainda está vazia. Adicione o primeiro veículo.</div>}</div></div>
    {open&&<div className="overlay" onMouseDown={()=>setOpen(false)}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setOpen(false)}><X/></button><span className="eyebrow">NOVA PUBLICAÇÃO</span><h2>Adicionar à fila</h2><p>Escolha o veículo e o perfil local. A extensão seguirá as etapas habilitadas em Configurações.</p><form onSubmit={enqueue}><label><FieldLabel help="Somente veículos ainda não marcados como Publicado aparecem nesta lista.">Veículo</FieldLabel><select name="vehicleId" required><option value="">Selecione</option>{vehicles.filter(v=>v.status!=='Publicado'&&v.status!=='Vendido').map(v=><option key={v.id} value={v.id}>{v.year} {v.make} {v.model}</option>)}</select></label><label><FieldLabel help="Cada perfil representa uma sessão local separada do Brave. O trabalho aparecerá somente quando este perfil estiver selecionado na extensão.">Perfil do Brave</FieldLabel><select name="accountId" required><option value="">Selecione o perfil responsável</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><div className="drawer-submit-help"><HelpTip tone="warning" text="Confira em Configurações se Avançar, grupos e Publicar devem ser automáticos para esta operação."/><button className="primary">Adicionar à fila</button></div></form></aside></div>}
  </section>
}
function JobBadge({status}:{status:string}){const labels:Record<string,string>={pending:'Pendente',filling:'Preenchendo',awaiting_confirmation:'Aguardando confirmação',completed:'Concluída',error:'Erro',canceled:'Cancelada',removed:'Anúncio removido'};return <span className={`job-badge ${status}`}>{labels[status]||status}</span>}
function JobReport({job}:{job:Job}){if(job.fillReport){const review=[...job.fillReport.missing,...(job.fillReport.missingGroups||[]).map(group=>`Grupo: ${group}`)];return <small className={review.length?'job-report warning':'job-report'} title={review.length?`Revisar: ${review.join(', ')}`:'Fluxo concluído sem pendências'}>{job.fillReport.filledCount}/{job.fillReport.totalCount} campos · {job.fillReport.imageCount} fotos{job.fillReport.selectedGroups?.length?` · ${job.fillReport.selectedGroups.length} grupos`:''}{job.fillReport.published?' · publicado automaticamente':job.fillReport.advanced?' · avançou':''}{job.extensionVersion?` · ext. ${job.extensionVersion}`:''}</small>}if(job.errorCode)return <small className="job-report error">{job.errorCode}</small>;return null}

export function ReportsView({api,vehicles}:{api:ApiFn;vehicles:Vehicle[]}) {
  const [jobs,setJobs]=useState<Job[]>([]),[period,setPeriod]=useState('30'),[seller,setSeller]=useState('Todos'),[loading,setLoading]=useState(true)
  const [reportNow]=useState(()=>Date.now())
  useEffect(()=>{api('/publications').then(result=>setJobs(result.jobs)).finally(()=>setLoading(false))},[])
  const sellers=useMemo(()=>['Todos',...new Set([...vehicles.map(vehicle=>vehicle.seller),...jobs.map(job=>job.seller)])],[vehicles,jobs])
  const scopedVehicles=useMemo(()=>vehicles.filter(vehicle=>seller==='Todos'||vehicle.seller===seller),[vehicles,seller])
  const scopedJobs=useMemo(()=>{
    const cutoff=period==='all'?0:reportNow-Number(period)*86400000
    return jobs.filter(job=>(seller==='Todos'||job.seller===seller)&&(!cutoff||new Date(`${job.createdAt}Z`).getTime()>=cutoff))
  },[jobs,period,seller,reportNow])
  const total=scopedVehicles.length
  const inventoryValue=scopedVehicles.reduce((sum,vehicle)=>sum+Number(vehicle.price||0),0)
  const averagePrice=total?inventoryValue/total:0
  const publishedVehicles=scopedVehicles.filter(vehicle=>vehicle.status==='Publicado').length
  const attentionVehicles=scopedVehicles.filter(vehicle=>vehicle.status==='Atenção').length
  const withPhotos=scopedVehicles.filter(vehicle=>Number(vehicle.imageCount||0)>0).length
  const photoCoverage=total?Math.round(withPhotos/total*100):0
  const completed=scopedJobs.filter(job=>job.status==='completed'||job.status==='removed').length
  const errors=scopedJobs.filter(job=>job.status==='error').length
  const active=scopedJobs.filter(job=>['pending','filling','awaiting_confirmation'].includes(job.status)).length
  const successRate=scopedJobs.length?Math.round(completed/scopedJobs.length*100):0
  const automatic=scopedJobs.filter(job=>job.fillReport?.published).length
  const groupsSelected=scopedJobs.reduce((sum,job)=>sum+(job.fillReport?.selectedGroups?.length||0),0)
  const byStatus=['Publicado','Pronto','Rascunho','Atenção','Vendido'].map(status=>({label:status,count:scopedVehicles.filter(vehicle=>vehicle.status===status).length}))
  const maxStatus=Math.max(1,...byStatus.map(item=>item.count))
  const funnel=[
    {label:'Trabalhos criados',count:scopedJobs.length,tone:'blue'},
    {label:'Em andamento',count:active,tone:'amber'},
    {label:'Concluídos',count:completed,tone:'green'},
    {label:'Com erro',count:errors,tone:'red'},
  ]
  const sellerPerformance=[...new Set(scopedJobs.map(job=>job.seller))].map(name=>{const own=scopedJobs.filter(job=>job.seller===name),done=own.filter(job=>['completed','removed'].includes(job.status)).length;return{name,total:own.length,done,rate:own.length?Math.round(done/own.length*100):0}}).sort((a,b)=>b.done-a.done||b.total-a.total)
  const profilePerformance=[...new Set(scopedJobs.map(job=>job.accountLabel))].map(name=>{const own=scopedJobs.filter(job=>job.accountLabel===name),done=own.filter(job=>['completed','removed'].includes(job.status)).length,fail=own.filter(job=>job.status==='error').length;return{name,total:own.length,done,fail,rate:own.length?Math.round(done/own.length*100):0}}).sort((a,b)=>b.total-a.total)
  const recent=[...scopedJobs].sort((a,b)=>new Date(`${b.createdAt}Z`).getTime()-new Date(`${a.createdAt}Z`).getTime()).slice(0,8)
  const periodLabel=period==='all'?'todo o histórico':`últimos ${period} dias`
  if(loading)return <section className="content"><div className="empty">Carregando relatórios...</div></section>
  return <section className="content reports-page"><div className="title-row"><div><span className="page-kicker">INTELIGÊNCIA OPERACIONAL</span><h1>Relatórios</h1><p>Estoque atual e desempenho das publicações para orientar a operação.</p></div><button className="secondary" onClick={()=>window.print()}><BarChart3 size={17}/>Imprimir relatório</button></div>
    <div className="report-filters"><div><Filter/><span>Filtros</span></div><label>Período das publicações<select value={period} onChange={event=>setPeriod(event.target.value)}><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="all">Todo o histórico</option></select></label><label>Responsável<select value={seller} onChange={event=>setSeller(event.target.value)}>{sellers.map(name=><option key={name}>{name}</option>)}</select></label><small>Estoque: posição atual · Publicações: {periodLabel}</small></div>
    <div className="report-kpis rich-kpis">
      <article><span className="kpi-icon"><WalletCards/></span><div><span>Valor em estoque</span><strong>{money.format(inventoryValue)}</strong><small>{total} veículo{total===1?'':'s'} no recorte</small></div></article>
      <article><span className="kpi-icon"><TrendingUp/></span><div><span>Preço médio</span><strong>{money.format(averagePrice)}</strong><small>Média do estoque atual</small></div></article>
      <article><span className="kpi-icon"><Car/></span><div><span>Estoque publicado</span><strong>{total?Math.round(publishedVehicles/total*100):0}%</strong><small>{publishedVehicles} publicado{publishedVehicles===1?'':'s'} · {attentionVehicles} em atenção</small></div></article>
      <article><span className="kpi-icon"><Camera/></span><div><span>Cobertura de fotos</span><strong>{photoCoverage}%</strong><small>{withPhotos} de {total} com pelo menos uma foto</small></div></article>
      <article><span className="kpi-icon"><Check/></span><div><span>Taxa de conclusão</span><strong>{successRate}%</strong><small>{completed} concluída{completed===1?'':'s'} em {scopedJobs.length} trabalho{scopedJobs.length===1?'':'s'}</small></div></article>
      <article><span className="kpi-icon"><Send/></span><div><span>Automação utilizada</span><strong>{automatic}</strong><small>{groupsSelected} seleções de grupos registradas</small></div></article>
    </div>
    <div className="report-grid primary-report-grid">
      <article className="module-card"><div className="module-head"><div><h2>Funil de publicação</h2><span>Movimentações em {periodLabel}</span></div></div><div className="funnel-list">{funnel.map((item,index)=><div key={item.label}><span className={`funnel-index ${item.tone}`}>{index+1}</span><div><strong>{item.label}</strong><small>{scopedJobs.length?Math.round(item.count/scopedJobs.length*100):0}% dos trabalhos no recorte</small></div><b>{item.count}</b></div>)}</div></article>
      <article className="module-card"><div className="module-head"><div><h2>Distribuição do estoque</h2><span>Veículos por situação atual</span></div></div><div className="bars status-bars">{byStatus.map(item=><div key={item.label}><div><span>{item.label}</span><strong>{item.count}</strong></div><i><b style={{width:`${item.count/maxStatus*100}%`}}/></i></div>)}</div></article>
    </div>
    <div className="report-grid secondary-report-grid">
      <article className="module-card"><div className="module-head"><div><h2>Qualidade das fotos</h2><span>Cobertura do estoque atual</span></div></div><div className="photo-quality"><div className="coverage-ring" style={{'--coverage':`${photoCoverage*3.6}deg`} as React.CSSProperties}><span><strong>{photoCoverage}%</strong><small>cobertura</small></span></div><div><div><span>Sem fotos</span><strong>{total-withPhotos}</strong></div><div><span>1 a 4 fotos</span><strong>{scopedVehicles.filter(vehicle=>Number(vehicle.imageCount||0)>=1&&Number(vehicle.imageCount||0)<=4).length}</strong></div><div><span>5 a 9 fotos</span><strong>{scopedVehicles.filter(vehicle=>Number(vehicle.imageCount||0)>=5&&Number(vehicle.imageCount||0)<=9).length}</strong></div><div><span>10 ou mais</span><strong>{scopedVehicles.filter(vehicle=>Number(vehicle.imageCount||0)>=10).length}</strong></div></div></div></article>
      <article className="module-card"><div className="module-head"><div><h2>Desempenho por responsável</h2><span>Conclusões em {periodLabel}</span></div></div><div className="ranking-list">{sellerPerformance.length?sellerPerformance.slice(0,6).map(item=><div key={item.name}><span className="ranking-avatar">{item.name.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><div><strong>{item.name}</strong><small>{item.done} concluída{item.done===1?'':'s'} em {item.total}</small><i><b style={{width:`${item.rate}%`}}/></i></div><em>{item.rate}%</em></div>):<div className="mini-empty">Sem publicações no período.</div>}</div></article>
    </div>
    <article className="module-card profile-performance"><div className="module-head"><div><h2>Desempenho por perfil do Brave</h2><span>Volume, conclusões e erros no período</span></div></div><div className="profile-metrics">{profilePerformance.length?profilePerformance.map(item=><div key={item.name}><div><Laptop/><span><strong>{item.name}</strong><small>{item.total} trabalho{item.total===1?'':'s'} processado{item.total===1?'':'s'}</small></span></div><span><b>{item.done}</b><small>concluídos</small></span><span className={item.fail?'metric-alert':''}><b>{item.fail}</b><small>erros</small></span><span><b>{item.rate}%</b><small>conclusão</small></span></div>):<div className="mini-empty">Nenhuma atividade de perfil neste recorte.</div>}</div></article>
    <article className="module-card recent-operations"><div className="module-head"><div><h2>Operações recentes</h2><span>Últimos trabalhos no recorte selecionado</span></div><span className="source-freshness">Atualizado com os dados do painel</span></div><div className="table-wrap"><table><thead><tr><th>VEÍCULO</th><th>RESPONSÁVEL</th><th>PERFIL</th><th>RESULTADO</th><th>AUTOMAÇÃO</th><th>DATA</th></tr></thead><tbody>{recent.map(job=>{const review=[...(job.fillReport?.missing||[]),...(job.fillReport?.missingGroups||[]).map(group=>`Grupo: ${group}`)];return <tr key={job.id}><td><strong>{job.year} {job.make} {job.model}</strong><small className="table-sub">Trabalho #{job.id}</small></td><td>{job.seller}</td><td>{job.accountLabel}</td><td><JobBadge status={job.status}/>{review.length>0&&<small className="table-warning" title={review.join(', ')}>{review.length} pendência{review.length===1?'':'s'}</small>}</td><td>{job.fillReport?.published?<span className="automation-chip auto">Publicação automática</span>:job.fillReport?.advanced?<span className="automation-chip">Avançou</span>:<span className="muted">Manual</span>}</td><td className="muted">{new Date(`${job.createdAt}Z`).toLocaleDateString('pt-BR')}</td></tr>})}</tbody></table>{!recent.length&&<div className="empty">Nenhuma operação encontrada para os filtros selecionados.</div>}</div></article>
  </section>
}

export function SettingsView({api,onSaved,theme,onThemeChange}:{api:ApiFn;onSaved:()=>void;theme:'light'|'dark';onThemeChange:(theme:'light'|'dark')=>void}) {
  const [data,setData]=useState<any>(null),[message,setMessage]=useState('')
  const [autoAdvance,setAutoAdvance]=useState(false),[fillGroups,setFillGroups]=useState(false),[autoPublish,setAutoPublish]=useState(false)
  useEffect(()=>{api('/settings').then(result=>{setData(result);setAutoAdvance(Boolean(result.settings.autoAdvance));setFillGroups(Boolean(result.settings.fillGroups));setAutoPublish(Boolean(result.settings.autoPublish))})},[])
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const targetGroups=String(f.get('targetGroups')||'').split(/\r?\n/).map(value=>value.trim()).filter(Boolean);try{await api('/settings',{method:'PATCH',body:JSON.stringify({organizationName:f.get('organizationName'),defaultLocation:f.get('defaultLocation'),dailyLimit:Number(f.get('dailyLimit')),autoAdvance,fillGroups,targetGroups,autoPublish,descriptionTemplate:f.get('descriptionTemplate')})});setMessage('Configurações salvas com sucesso.');onSaved()}catch(err){setMessage(err instanceof Error?err.message:'Erro ao salvar')}}
  if(!data)return <section className="content"><div className="empty">Carregando configurações...</div></section>
  return <section className="content settings-page"><div className="title-row"><div><span className="page-kicker">ADMINISTRAÇÃO</span><h1>Configurações</h1><p>Personalize a empresa e os controles de publicação.</p></div></div>{message&&<div className="inline-message success">{message}<button onClick={()=>setMessage('')}><X/></button></div>}
    <form onSubmit={save}><article className="settings-card"><div className="settings-icon"><Settings/></div><div className="settings-content"><h2>Dados da empresa</h2><p>Identificação exibida para todos os usuários.</p><div className="settings-fields"><label><FieldLabel help="Nome exibido no painel para todos os integrantes desta organização.">Nome da empresa</FieldLabel><input name="organizationName" defaultValue={data.organization.name} required/></label><label><FieldLabel help="Valor sugerido nos novos veículos; pode ser alterado em cada cadastro.">Localização padrão</FieldLabel><input name="defaultLocation" defaultValue={data.settings.defaultLocation}/></label></div></div></article>
      <article className="settings-card"><div className="settings-icon"><Send/></div><div className="settings-content"><h2>Fluxo do Marketplace</h2><p>Escolha exatamente até onde a extensão deve conduzir cada anúncio.</p><div className="automation-options">
        <label className="toggle-label"><span><span className="field-label"><strong>Avançar automaticamente</strong><HelpTip text="Depois de preencher e validar os dados do veículo, pressiona Avançar para abrir a etapa de grupos."/></span><small>Sem esta opção, o fluxo termina no primeiro formulário</small></span><input name="autoAdvance" type="checkbox" checked={autoAdvance} onChange={event=>{setAutoAdvance(event.target.checked);if(!event.target.checked){setFillGroups(false);setAutoPublish(false)}}}/></label>
        <label className="toggle-label"><span><span className="field-label"><strong>Selecionar grupos configurados</strong><HelpTip text="Marca somente grupos cujo nome corresponda exatamente à lista abaixo. Grupos não encontrados interrompem a publicação automática."/></span><small>{autoAdvance?'Seleciona os grupos na segunda etapa':'Ative primeiro o avanço automático'}</small></span><input name="fillGroups" type="checkbox" checked={fillGroups} disabled={!autoAdvance} onChange={event=>setFillGroups(event.target.checked)}/></label>
        <label className="group-list-field"><FieldLabel help="Use o nome exibido no Facebook, respeitando palavras e pontuação. Um grupo por linha; máximo de 20.">Grupos a selecionar</FieldLabel><textarea name="targetGroups" rows={6} disabled={!fillGroups} defaultValue={(data.settings.targetGroups||[]).join('\n')} placeholder={'Compra-se e Vende-se\nVENDAS SÃO LUDGERO\nCarros e Motos Criciúma e Região'}/><small>Um nome exato por linha · até 20 grupos</small></label>
        <label className="toggle-label publish-toggle"><span><span className="field-label"><strong>Publicar automaticamente</strong><HelpTip tone="warning" text="Quando ligado, a extensão pressiona Publicar somente se todos os campos e grupos configurados forem confirmados. Deixe desligado para revisar manualmente."/></span><small>{autoAdvance?'Desligue para manter o clique final manual':'Ative primeiro o avanço automático'}</small></span><input name="autoPublish" type="checkbox" checked={autoPublish} disabled={!autoAdvance} onChange={event=>setAutoPublish(event.target.checked)}/></label>
      </div><div className="settings-fields"><label><FieldLabel help="Limite operacional interno por perfil. Use um valor compatível com a rotina da equipe e revise qualquer alerta do Facebook.">Limite diário por perfil</FieldLabel><input name="dailyLimit" type="number" min="1" max="50" defaultValue={data.settings.dailyLimit}/><small>Entre 1 e 50 publicações</small></label></div><label><FieldLabel help="Texto-base aplicado à descrição. As variáveis entre chaves são substituídas pelos dados do veículo.">Modelo de descrição</FieldLabel><textarea name="descriptionTemplate" rows={4} defaultValue={data.settings.descriptionTemplate}/><small>Variáveis disponíveis: {'{ano} {marca} {modelo} {versao} {km}'}</small></label></div></article>
      <article className="settings-card"><div className="settings-icon"><Palette/></div><div className="settings-content"><h2>Aparência</h2><p>O tema é salvo somente neste navegador.</p><div className="theme-options"><button type="button" className={theme==='light'?'selected':''} onClick={()=>onThemeChange('light')}><span><Sun/></span><div><strong>Tema claro</strong><small>Maior luminosidade</small></div><Check/></button><button type="button" className={theme==='dark'?'selected':''} onClick={()=>onThemeChange('dark')}><span><Moon/></span><div><strong>Tema escuro</strong><small>Conforto em ambientes escuros</small></div><Check/></button></div></div></article>
      <article className="settings-card security-settings"><div className="settings-icon"><ShieldCheck/></div><div className="settings-content"><h2>Segurança das contas</h2><p>Credenciais do Facebook não são aceitas nem armazenadas. Cada sessão permanece no perfil local do Brave utilizado pelo vendedor.</p><div className="policy-row"><Check/><span>Cookies e senhas fora do servidor</span></div><div className="policy-row"><Check/><span>Interrupção automática quando campos ou grupos falham</span></div></div></article><div className="settings-save"><button className="primary"><Save size={17}/>Salvar configurações</button></div></form>
  </section>
}
